INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE)
    VALUES ('인텔리제이 강의 듣기', 'Ch01 끝내기', 'In_PROGRESS', now() + 1);

INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE)
    VALUES ('인텔리제이 강의 듣기', 'Ch02 끝내기', 'TODO', now() + 2);